### ISSUE TITLE
Add `--base-path` CLI option to override the URL path in the tilejson

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1185]
As discussed in #1184, Martin should have an option to override the base path when its being hosted behind a proxy that cannot easily set `x-rewrite-url` header.

## CLI parameter

```shell
# Force Martin to ignore the x-rewrite-url header and set tilejson's tiles URL
# as   <protocol>://<host>/<source>/{z}/{x}/{y}
martin --base-path /

# Force it to be  <protocol>://<host>/foo/bar/<source>/{z}/{x}/{y}
martin --base-path /foo/bar

# This should work the same as above
martin --base-path /foo/bar/

# This should produce an error
# (must start with a slash, but could be relaxed in the future, e.g. can combine path with x-rewrite-uri?)
martin --base-path foo/bar
```

## Configuration Files

Add `base_path` to the root (in the `struct SrvConfig`)

```yaml
---
base_path: /foo/bar
```

## Code changes
- [ ] Add `base_path: Option<String>` to [SrvArgs](https://github.com/maplibre/martin/blob/79a89125edd6529177b00bca8d09fc9e9fb898a5/martin/src/args/srv.rs#L5) - similar to how `listen_addresses` is implemented
- [ ] Add `base_path` to [SrvConfig](https://github.com/maplibre/martin/blob/main/martin/src/srv/config.rs#L8)
- [ ] Similar to catalog, pass `Data::new(config)` to the `app_data` in [new_server](https://github.com/maplibre/martin/blob/79a89125edd6529177b00bca8d09fc9e9fb898a5/martin/src/srv/server.rs#L126)
- [ ] Modify [`get_source_info`](https://github.com/maplibre/martin/blob/79a89125edd6529177b00bca8d09fc9e9fb898a5/martin/src/srv/tiles_info.rs#L28) to additionally take `config: Data<SrvConfig>` and use it to override the `x-rewrite-url` handling.
- [ ] Make sure [`finalize`](https://github.com/maplibre/martin/blob/79a89125edd6529177b00bca8d09fc9e9fb898a5/martin/src/config.rs#L73) does all the needed validations of this value or it should return an error. You will need to add a new error to `MartinError` for this.

**Comment by sharkAndshark** [comment]
Do we need to add it to config either?

**Comment by nyurik** [comment]
@sharkAndshark I just updated this ticket with all the details needed

**Comment by sutanAE** [comment]
> Do we need to add it to config either?

It would be nice to add this on config.

In my experience, I put Martin behind NGINX and use the ```proxy_pass``` directive, and rewrite the basepath. the SSL can be handled on NGINX as well. This works with ```/tablename/{z}/{x}/{y}```, however, this won't work with the ```tile.json``` because there is no base path for martin. If we could add this, then it would be so nice!

**Comment by nyurik** [comment]
Yep, I documented it above for both CLI and config file case.  @sutanAE, if you use NGINX, why not use [rewriting urls](https://maplibre.org/martin/run-with-nginx.html#rewriting-urls) config?

**Comment by nyurik** [comment]
Should this feature ignore X-REWRITE-URL header if it is set? I.e. override it?  Or should it only work if there is no x-rewrite-url header?  What usecases would there be for its usage?

**Comment by sutanAE** [comment]
> Yep, I documented it above for both the CLI and config file cases. @sutanAE, if you use NGINX, why not use [rewriting urls](https://maplibre.org/martin/run-with-nginx.html#rewriting-urls) config?

Hi @nyurik thank you. That is because I did not read the documentation correctly; my apologies. 

It seems like the problem is now solved for me. Either way, I think it would still be nice to have something that acts as a base path for Martin. The only thing I can think of is why the developer experience and local development imitates NGINX configuration.

I personally develop my app using Node.js with SvelteKit and have Martin running on another port. Martin's URL in localhost and production is different, so the SvelteKit's code is quite messy; there are lots of ```if``` statements to see if it's in dev or in prod. Of course, this could be avoided using environment variables, but this limits Martin to certain styles.

I hope I am contributing to the discussion—many thanks for developing such amazing software.
