### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by maxammann** [urbica/martin#410]
We should create a new release on Github soon, so users can at least benefit from updated dependencies.

I can also look into it if I find the time :)

**Comment by gbip** [comment]
That would be great !

**Comment by tjni** [comment]
This is timely. There is more need for it now, because `v0.5.0` depends on `socket2@0.3.11`, and it does not build on Rust 1.64 after https://github.com/rust-lang/rust/pull/78802. It's only fixed in `socket2@0.3.16`.

I ran into this since [nixpkgs](https://github.com/NixOS/nixpkgs) is updating to Rust 1.64. In the meantime, I intend to patch it inside of the nixpkgs build, but it will become harder and harder to do this in the future.

**Comment by nyurik** [comment]
Hi, I would love to do a release, esp that now we have tons of new changes, but I'm a bit worried about #423 -- somehow docker build became unstable on some machines, and I do not know what is causing it (and if we can automate integration testing for that)

**Comment by nyurik** [comment]
v0.6.1 was released last week!
