### ISSUE TITLE
Docker: can't reach Martin server

### ISSUE THREAD

**Issue by asindl** [urbica/martin#954]
Hi there, 
I wanted to try out Martin server and deployed it as Docker image to a K8s cluster.
Things seem to work alright, in the log messages I can see the auto-discovery of my geospatial tables.
But I can't reach the Martin server.
Could the problem be related to the last log entry?
```
WARN martin::pg::config] Discovering tables in PostgreSQL database 'xyz' is taking too long. Make sure your table geo columns have a GIS index, or use --disable-bounds CLI/config to skip bbox calculation.
```
All tables have a geo column...

**Comment by nyurik** [comment]
Yes, you can't reach it because it hasn't started yet - it is still trying to find the tables/functions you have in your postgres, and it is taking too long (good thing we added that warning :)) -- i would suggest to follow the suggestion, but before that - when martin is just starting, check which queries are currently running in postgres, esp the long running ones, and see why it is taking so long.

**Comment by asindl** [comment]
You are right: 20 minutes later, the server was started.
I will close the question.
Thanks!

**Comment by nyurik** [comment]
yeah, clearly something is wrong with your data - check the long running queries, you will know which table has no GIS index.
